TEMPERATURE_BUFFER_LENGTH       = 10
TEMPERATURE_UPDATE_PERIOD_S     = 5
DHT11_GPIO_NUM                  = 28

SOCKET_UPDATE_PERIOD_S          = 10
SOCKET_PORT_NUMBER              = 5000
SOCKET_MAX_CLIENTS              = 2

MAX_THREADPOOL_WORKERS          = 2
